-- =============================================================================
-- Seed data for local development and testing
--
-- This file is loaded by `supabase db reset` (local dev) or run manually
-- against a staging project. It MUST NOT be applied to production.
--
-- The fake mcp_token below is intentionally short and obviously fake so it
-- cannot be confused with a real token. Real tokens generated by the
-- dashboard will be cryptographically random and much longer.
--
-- Usage (local Supabase CLI):
--   supabase db reset          -- resets + runs migrations + seed
--   psql $DATABASE_URL -f supabase/seed.sql  -- seed only
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Test user
--
-- Represents a developer who has:
--   - Connected their Stripe card (stripe_card payment method)
--   - Set a $5 auto-charge threshold (deploys up to $5 need no confirmation)
--   - A fake Vercel token for local stub testing
--   - A known mcp_token to paste into Claude Code config during dev
-- ---------------------------------------------------------------------------

INSERT INTO users (
  id,
  email,
  payment_method,
  payment_provider_customer_id,
  stripe_customer_id,
  mcp_token,
  vercel_token,
  max_auto_charge_usd,
  created_at,
  updated_at
) VALUES (
  '00000000-0000-0000-0000-000000000001',   -- fixed UUID for predictable test queries
  'dev-test@spendexpay.local',
  'stripe_card',
  'cus_test_localdev_stripe',               -- fake Stripe customer ID (prefix "cus_test_")
  'cus_test_localdev_stripe',               -- mirrors payment_provider_customer_id for stripe_card
  'spx_test_localdev_mcptoken_abc123',      -- paste this into .env / Claude Code config
  'vercel_test_localdev_token_xyz789',      -- fake Vercel token (rejected by real Vercel API)
  5.00,                                     -- auto-approve charges up to $5.00
  now(),
  now()
)
ON CONFLICT (id) DO NOTHING;  -- idempotent: safe to run seed.sql multiple times

-- ---------------------------------------------------------------------------
-- Spending rules for the test user
--
-- max_auto_charge_usd mirrors the users row (the users column is a cache for
-- fast reads; this table is authoritative).
-- monthly_budget_usd of $50 prevents runaway charges in local dev scenarios
-- where the payment stub always succeeds.
-- allowed_services is empty = all services permitted.
-- ---------------------------------------------------------------------------

INSERT INTO spending_rules (
  id,
  user_id,
  max_auto_charge_usd,
  monthly_budget_usd,
  allowed_services,
  created_at,
  updated_at
) VALUES (
  '00000000-0000-0000-0000-000000000002',
  '00000000-0000-0000-0000-000000000001',
  5.00,
  50.00,
  '{}',   -- all services permitted in local dev
  now(),
  now()
)
ON CONFLICT (user_id) DO NOTHING;  -- spending_rules.user_id is UNIQUE

-- ---------------------------------------------------------------------------
-- Sample wallet row for the test user
--
-- Demonstrates the wallets table shape. In production, wallets are created
-- by the dashboard when the user adds additional payment methods.
-- ---------------------------------------------------------------------------

INSERT INTO wallets (
  id,
  user_id,
  provider,
  provider_customer_id,
  is_default,
  created_at
) VALUES (
  '00000000-0000-0000-0000-000000000003',
  '00000000-0000-0000-0000-000000000001',
  'stripe_card',
  'cus_test_localdev_stripe',
  true,   -- this is the default wallet, matching users.payment_method
  now()
)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Sample audit log entry
--
-- A successful $0 Vercel deploy — the typical transaction shape for the
-- deploy_to_vercel tool while VERCEL_DEPLOY_COST_USD = 0.
-- Useful for verifying that the dashboard billing history renders correctly.
-- ---------------------------------------------------------------------------

INSERT INTO audit_logs (
  id,
  user_id,
  service,
  status,
  amount_usd,
  description,
  transaction_id,
  error_message,
  created_at
) VALUES (
  '00000000-0000-0000-0000-000000000010',
  '00000000-0000-0000-0000-000000000001',
  'vercel',
  'success',
  0.00,
  'Vercel deploy: my-test-project',
  'pi_test_localdev_paymentintent',   -- fake Stripe PaymentIntent ID
  NULL,
  now() - interval '1 hour'          -- back-dated so it appears in history
)
ON CONFLICT (id) DO NOTHING;

-- A sample payment_failed entry to verify error display in the dashboard.
INSERT INTO audit_logs (
  id,
  user_id,
  service,
  status,
  amount_usd,
  description,
  transaction_id,
  error_message,
  created_at
) VALUES (
  '00000000-0000-0000-0000-000000000011',
  '00000000-0000-0000-0000-000000000001',
  'vercel',
  'payment_failed',
  0.00,
  'Vercel deploy: my-test-project',
  NULL,                               -- no transaction ID: payment never reached provider
  'Your card was declined.',
  now() - interval '2 hours'
)
ON CONFLICT (id) DO NOTHING;
